export interface ExploreItem {
  id: string
  title: string
  author: string
  description: string
  category: string
  tags: string[]
  starkz: number
  comments: number
  publishedAt: string
  price: number
  type: "Article" | "Course" | "eBook" | "NFT"
  readTime?: string
  image?: string
}

export const exploreMockData: ExploreItem[] = [
  {
    id: "1",
    title: "Introduction to Blockchain Technology",
    author: "Alice Johnson",
    description: "A comprehensive guide to understanding the basics of blockchain technology and its applications.",
    category: "Technology",
    tags: ["Blockchain", "Cryptocurrency", "Decentralization"],
    starkz: 1250,
    comments: 45,
    publishedAt: "2023-06-15T10:00:00Z",
    price: 0.05,
    type: "Article",
    readTime: "8 min read",
    image: "/blockchain-technology-digital-network.jpg",
  },
  {
    id: "2",
    title: "Advanced Machine Learning Techniques",
    author: "Bob Smith",
    description: "Explore cutting-edge machine learning algorithms and their practical implementations.",
    category: "Data Science",
    tags: ["Machine Learning", "AI", "Data Analysis"],
    starkz: 980,
    comments: 32,
    publishedAt: "2023-06-18T14:30:00Z",
    price: 0.1,
    type: "Course",
    readTime: "12 min read",
    image: "/ml-neural-network-visualization.png",
  },
  {
    id: "3",
    title: "The Future of Decentralized Finance",
    author: "Carol Williams",
    description: "An in-depth look at the evolving landscape of DeFi and its potential impact on traditional finance.",
    category: "Finance",
    tags: ["DeFi", "Blockchain", "Cryptocurrency"],
    starkz: 1500,
    comments: 67,
    publishedAt: "2023-06-20T09:15:00Z",
    price: 0.08,
    type: "eBook",
    readTime: "15 min read",
    image: "/decentralized-finance-cryptocurrency.jpg",
  },
  {
    id: "4",
    title: "Quantum Computing Explained",
    author: "David Brown",
    description: "Demystifying quantum computing and its potential applications in various industries.",
    category: "Technology",
    tags: ["Quantum Computing", "Physics", "Technology"],
    starkz: 750,
    comments: 28,
    publishedAt: "2023-06-22T11:45:00Z",
    price: 0.07,
    type: "Article",
    readTime: "10 min read",
    image: "/quantum-computing-qubits-technology.jpg",
  },
  {
    id: "5",
    title: "Sustainable Energy Solutions",
    author: "Emma Davis",
    description: "Exploring innovative approaches to renewable energy and sustainable development.",
    category: "Environment",
    tags: ["Renewable Energy", "Sustainability", "Climate Change"],
    starkz: 1100,
    comments: 41,
    publishedAt: "2023-06-25T16:20:00Z",
    price: 0.06,
    type: "Course",
    readTime: "14 min read",
    image: "/renewable-energy-solar-panels-wind-turbines.jpg",
  },
  {
    id: "6",
    title: "Cybersecurity in the Digital Age",
    author: "Frank Miller",
    description: "Understanding modern cybersecurity threats and effective protection strategies.",
    category: "Technology",
    tags: ["Cybersecurity", "Digital Privacy", "Hacking"],
    starkz: 890,
    comments: 35,
    publishedAt: "2023-06-28T13:10:00Z",
    price: 0.09,
    type: "eBook",
    readTime: "11 min read",
    image: "/cybersecurity-digital-lock-network-security.jpg",
  },
  {
    id: "7",
    title: "The Art of Data Visualization",
    author: "Grace Lee",
    description: "Learn how to create compelling and informative data visualizations using modern tools.",
    category: "Data Science",
    tags: ["Data Visualization", "Analytics", "Design"],
    starkz: 1300,
    comments: 52,
    publishedAt: "2023-07-01T10:30:00Z",
    price: 0.07,
    type: "Course",
    readTime: "13 min read",
    image: "/data-visualization-charts-graphs-analytics.jpg",
  },
  {
    id: "8",
    title: "Exploring the Metaverse",
    author: "Henry Wilson",
    description: "A journey into the concept of the metaverse and its potential impact on society.",
    category: "Technology",
    tags: ["Metaverse", "Virtual Reality", "Augmented Reality"],
    starkz: 950,
    comments: 38,
    publishedAt: "2023-07-03T15:45:00Z",
    price: 0.08,
    type: "Article",
    readTime: "9 min read",
    image: "/metaverse-digital-world.png",
  },
  {
    id: "9",
    title: "Genetic Engineering and Ethics",
    author: "Isabel Rodriguez",
    description: "Examining the ethical implications of advances in genetic engineering and biotechnology.",
    category: "Science",
    tags: ["Genetics", "Bioethics", "Biotechnology"],
    starkz: 800,
    comments: 29,
    publishedAt: "2023-07-06T12:20:00Z",
    price: 0.06,
    type: "eBook",
    readTime: "12 min read",
    image: "/genetic-engineering-dna-biotechnology.jpg",
  },
  {
    id: "10",
    title: "The Psychology of Decision Making",
    author: "Jack Thompson",
    description: "Understanding the cognitive processes behind human decision making and their applications.",
    category: "Psychology",
    tags: ["Decision Making", "Cognitive Psychology", "Behavioral Economics"],
    starkz: 1050,
    comments: 44,
    publishedAt: "2023-07-09T14:00:00Z",
    price: 0.07,
    type: "Course",
    readTime: "10 min read",
    image: "/psychology-brain-decision-making-cognitive.jpg",
  },
]

export const categories = Array.from(new Set(exploreMockData.map((item) => item.category)))
export const tags = Array.from(new Set(exploreMockData.flatMap((item) => item.tags)))
export const types = Array.from(new Set(exploreMockData.map((item) => item.type)))
